apiVersion: apps/v1
kind: Deployment
metadata:
  name: validating-webhook-deployment
  labels:
    app: validating-webhook
  namespace: webhooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validating-webhook
  template:
    metadata:
      labels:
        app: validating-webhook
    spec:
      containers:
      - name: webhook
        image: "YOUR_BUILT_IMAGE" # keep your built image, store in a container registry
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/webhook/certs
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: validating-webhook-certs