apiVersion: v1
kind: Service
metadata:
  name: validating-webhook-service
  namespace: webhooks
spec:
  selector:
    app: validating-webhook
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443