apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-label-validator-webhook
webhooks:
- name: pod-label-validator.example.com
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    service:
      name: validating-webhook-service
      namespace: webhooks
      path: "/validate"
    # IMPORTANT: You MUST paste the base64-encoded CA bundle here.
    caBundle: "ENCODED_CA"
  admissionReviewVersions: ["v1"]
  sideEffects: None
  failurePolicy: Fail # Use 'Ignore' if you want to allow requests even if the webhook is down